site_description: Hakai hub for any topics related to data distribution.
site_name: Hakai Catalogue Checks
site_url: https://data.hakai.org
repo_url: https://github.com/HakaiInstitute/hakai-ckan-records-checks
repo_name: HakaiInstitute/hakai-ckan-records-checks
copyright: Copyright &copy; Hakai Institute

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom
      primary: "anything"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "anything"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs

plugins:
  - plotly
  - search

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly

extra_css:
  - assets/stylesheets/extra.css
  - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
  - https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.5.1.js
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/HakaiInstitute