site_description: Hakai hub for any topics related to data distribution.
site_name: Hakai Catalogue Checks
site_url: https://data.hakai.org
repo_url: https://github.com/HakaiInstitute/hakai-ckan-records-checks
repo_name: HakaiInstitute/hakai-ckan-records-checks
copyright: Copyright &copy; Hakai Institute

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom
      primary: "anything"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "anything"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - content.tabs.link

plugins:
  - plotly
  - search
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
  - https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css
  - assets/stylesheets/extra.css

extra_javascript:
  - https://code.jquery.com/jquery-3.5.1.js
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.js
  - https://cdn.datatables.net/2.0.8/js/dataTables.min.js

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/HakaiInstitute