name: Hakai CKAN Record Checks

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      VERSION: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.CI_TOKEN }}
          fetch-depth: 0

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12

      - name: Install dependencies
        run: uv sync --group dev

      - if: (github.event_name != 'pull_request' && github.event_name != 'push')
        name: Run Hakai CKAN Record Checks
        run: uv run hakai_ckan_records_checks -c https://catalogue.hakai.org --no-cache

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9
        with:
          commit_message: "Update records [skip ci]"

      - name: Build the site
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git fetch origin gh-pages --depth=1
          uv run mike deploy "${VERSION}" --push
          uv run mike set-default main --push

