name: Hakai CKAN Record Checks

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install .

      - name: Run Hakai CKAN Record Checks
        run: python hakai_ckan_records_checks -c https://catalogue.hakai.org --no-cache
      - name: Commit changes
        run: |
          git config --global user.name "Hakai Institute"
          git config --global user.email "
          git add .
          git commit -m "Update records"
          git push

      - name: Build site with mkdocs
        run: mkdocs build --site-dir site
      - name: Upload Page artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
  deploy:
    needs: build
    permissions:
      pages: write     
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
